var e=null,highlighter=new function(){function m(a,b,c){this.b=a;this.position=new x(0,0);this.k=b;this.color=c}function x(a,b){this.x=a;this.y=b}function N(a,b){this.content=a;this.n=a.toLowerCase().split(O);this.z=y(this.n);this.b=b;this.F=e}function P(a,b,c){this.g=a;this.q=b;this.m=c}function Q(a,b,c){this.x=a;this.y=b;this.color=c}function R(a,b,c,d){this.D=a;this.B=b;this.C=c;this.A=d}function y(a){for(var b=[],c=0;c<a.length;c++)r.setCurrent(a[c]),r.stem(),b[c]=r.getCurrent();return b}function S(a,
b){for(var c=0,d=0;d<b;d++)c+=a[d].length+1;return[c,a[b].length+c]}function T(a,b,c){for(var d=[],g=0;g<b.length;g++)for(var i=0;i<c.length;i++)if(b[g].indexOf(c[i])==0){var n=S(a,g);d.push(new P(n[0],n[1],i))}return d.sort(function(a,b){return a.g-b.g})}function E(){o=[];for(highlighter.a=[];;){var a=window.getComputedStyle(f,e),a=a==e||a.display!="none";if(f.childNodes.length>0&&a&&(f=f.childNodes[0],f.childNodes.length>0))continue;f.parentNode.nodeName!="SCRIPT"&&f.parentNode.nodeName!="NOSCRIPT"&&
f.parentNode.nodeName!="STYLE"&&f.parentNode.nodeName!="ADVANCEDSEARCH-DEL"&&f.parentNode.nodeName!="TEXTAREA"&&f.nodeType!=8&&a&&f.textContent!=e&&f.textContent.trim()!=""&&(o[o.length]=new N(f.textContent,f));if(f.nextSibling==e){for(;f!=U&&f.parentNode!=e;){var b=!1;if(f.parentNode.nextSibling!=e){f=f.parentNode.nextSibling;b=!0;break}f=f.parentNode}if(!b)break}else f=f.nextSibling}}function F(){var a=document.getElementById("advancedSearch-counter");if(a!=e)a.innerText=highlighter.a.length}function s(a){a=
G(a);H(a)}function G(a){a<0&&(a=0);a>=highlighter.a.length&&(a=highlighter.a.length-1);var b=a;if(k!=e){for(var c=-1,d=!1,g=-1,i=0;i<highlighter.a.length;i++)if(highlighter.a[i].k==k&&(c++,g=i),c==a){b=i;d=!0;break}d||(a=Math.min(c,a),g>0&&(b=g))}if(b<0)return-1;c=highlighter.a[b].position;if(highlighter.e!=e)highlighter.e.className="";highlighter.c=a;highlighter.e=highlighter.a[b].b;highlighter.e.className="advancedSearch-highlight";return c.y}function V(){var a=h();k=W(a.value,a.selectionStart,
a.selectionEnd);I()}function I(){var a="";k!=e&&(k=y([k.replace('"',"")])[0],a=z[k],a==e&&(a="",k=e));document.getElementById("advancedSearch-updown").style["border-color"]=a}function X(){var a=document.createElement("div");a.innerHTML='<div id="advancedSearch-div"><textarea rows="1" id="advancedSearch-searchBox"></textarea><div id="advancedSearch-updown"><div id="advancedSearch-up"></div><div id="advancedSearch-down"></div></div><div id="advancedSearch-x"></div><label id="advancedSearch-counter"></label><div id="advancedSearch-searchBoxCopy"></div></div><div id="advancedSearch-delWordButton"></div>';
document.body.appendChild(a);document.getElementById("advancedSearch-down").onclick=function(){s(highlighter.c+1)};document.getElementById("advancedSearch-up").onclick=function(){s(highlighter.c-1)};document.getElementById("advancedSearch-x").onclick=function(){J()};h().onclick=function(){setTimeout(V,100)};h().addEventListener("input",t)}function W(a,b,c){if(b<c)return a.substring(b,c).replace(/\s/g,"");if(b<=0)return e;if(b>=a.length)return e;if(a[b]==" ")return e;if(a[b-1]==" ")return e;for(var d=
c=-1,g=b;g>=0;g--){if(a[g]==" ")break;c=g}for(g=b;g<=a.length;g++)if(d=g,a[g]==" ")break;return a.substring(c,d)}function K(a){a=a.split(/[&?][qp]=/);if(a.length==1)return e;a=a.pop();return unescape(a.split("&")[0]).replace(/\++/g," ")}function t(){for(var a=h().value.replace(/\s/g," ").toLowerCase().split(" "),b=!1,c=[],d=-1,g=0;g<a.length;g++){var i=!0,n=!1,f=!0;b?(i=!1,n=!0,f=!1):d++;a[g].match('^"')!=e&&(i=b=!0,f=n=!1);a[g].match('"$')!=e&&(i=b=!1,f=!0,n=!1);a[g].length<=1?b||d--:a[g].replace(/"/ig,
"").length<=1?b||d--:c.push(new R(i,n,f,d))}L=c;b=[];for(c=0;c<a.length;c++)a[c].length<=1||(d=a[c].replace(/"/ig,""),d.length<=1||b.push(d));b=y(b);b.length==0?(highlighter.d(),searchBoxSettings.searchText="",A()):(highlighter.p(b),searchBoxSettings.searchText=h().value.trim());storeSearchBoxSettings(!1)}function h(){return document.getElementById("advancedSearch-searchBox")}function B(){if(h().value==""||h().value==C){var a=!searchBoxSettings.parseReferrer||document.referrer==e||document.referrer.length==
0?e:K(document.referrer);if(a!=e&&a.length>0)h().value=a.trim()}document.getElementById("advancedSearch-div").style.display="block";h().focus();h().value!=""&&t();searchBoxSettings.isOpen=!0;u();storeSearchBoxSettings(!1)}function J(){document.getElementById("advancedSearch-div").style.display="none";highlighter.d();highlighter.c=-1;k=e;highlighter.e=e;searchBoxSettings.isOpen=!1;storeSearchBoxSettings(!1);h().blur();p()}function H(a){for(var b=0;b<v.length;b++)clearTimeout(v[b]);if(!(a<0)){v=[];
var c=parseInt(a,10)-window.innerHeight/2,c=Math.max(0,c),b=window.pageYOffset,d=0,a=[],g=Math.abs(b-c),i=-1;c>b&&(i=1);for(c=0;d<6.5;c+=0.1)d=Math.sin(c+2)+c-1,d>0&&a.push(b+i*d/6.5*g);for(b=0;b<a.length;b++)v.push(setTimeout("window.scrollTo(0, "+a[b]+")",10*b))}}function A(){var a=document.getElementById("advancedSearch-scrollMarks");a!=e&&a.parentNode.removeChild(a)}function Y(){if(searchBoxSettings.showScrollbarMarkers){for(var a=[],b=0;b<highlighter.a.length;b++)a.push(new Q(highlighter.a[b].position.x,
highlighter.a[b].position.y,highlighter.a[b].color));a.sort(function(a,b){return a.y-b.y});var c=document.height;A();var d=e,d=document.createElement("div");d.id="advancedSearch-scrollMarks";document.body.appendChild(d);var g=document.createElement("table");d.appendChild(g);for(var d=100,i=-1E3,f="",b=0;b<a.length;b++)if(!(a[b].y-100<i&&a[b].color==f)){var i=a[b].y,f=a[b].color,h=document.createElement("tr"),j=document.createElement("td");j.className="advancedSearch-markerCell";var l=Math.floor(100*
a[b].y/c-(100-d));d-l<=3&&(l=d-3);d-=l;j.style.height=l+"%";l=document.createElement("div");l.className="advancedSearch-marker";l.setAttribute("targetpos",a[b].y);l.style["border-left-color"]=a[b].color;l.addEventListener("click",function(){H(this.getAttribute("targetpos"))},!1);j.appendChild(l);h.appendChild(j);g.appendChild(h)}a=document.createElement("tr");c=document.createElement("td");c.className="advancedSearch-markerCell";c.style.height=d+"%";a.appendChild(c);g.appendChild(a)}}function u(){highlighter.f=
!0;var a=h().value.split(" "),b=document.getElementById("advancedSearch-searchBoxCopy");b.innerHTML="";for(var c=0;c<a.length;c++){var d=document.createElement("advancedSearch-del");d.innerHTML=a[c]+"&nbsp";d.attributes.nth=c;b.appendChild(d)}M=highlighter.j(h());a=document.getElementById("advancedSearch-searchBoxCopy");b=h();a.style.left=window.getComputedStyle(b,e).left;a.style.width=b.offsetWidth-1+"px";a.scrollLeft=b.scrollLeft;a.style.font=window.getComputedStyle(b,e).font;a.style["font-size"]=
window.getComputedStyle(b,e)["font-size"];a.style["font-family"]=window.getComputedStyle(b,e)["font-family"];a.style["padding-left"]=window.getComputedStyle(b,e)["padding-left"];highlighter.f=!1}function Z(){var a=document.getElementById("advancedSearch-delWordButton").attributes.nth;p();var b=h().value.split(" ");a>0&&b[a].match(/"$/)!=e&&b[a].match(/^"/)==e&&(b[a-1]+='"');a<b.length-1&&b[a].match(/^"/)!=e&&b[a].match(/"$/)==e&&(b[a+1]='"'+b[a+1]);b[a]=e;h().value=b.join(" ").replace(/\s+/g," ").trim();
u();t()}function p(){var a=document.getElementById("advancedSearch-delWordButton");a.style.display="none";a.attributes.nth=e}function $(a){for(var b=document.getElementById("advancedSearch-searchBoxCopy"),c=0;c<b.childNodes.length;c++){var d=b.childNodes[c];if(d.nodeName=="ADVANCEDSEARCH-DEL"&&d.offsetLeft-b.scrollLeft<a.offsetX&&d.offsetLeft+d.offsetWidth-b.scrollLeft>a.offsetX){a=highlighter.j(d).x-b.scrollLeft;M.x>a?p():(b=document.getElementById("advancedSearch-delWordButton"),b.style.display=
"block",b.style.left=a+"px",b.attributes.nth=c,D>0&&clearTimeout(D),D=setTimeout(p,2E3));return}}p()}function aa(a){switch(a.which){case ba:J();break;case highlighter.v:(document.activeElement.nodeName=="INPUT"||document.activeElement.nodeName=="TEXTAREA")&&highlighter.r&&(q=e);searchBoxSettings.keySettings.doubleF||(q=e);if(new Date-q<searchBoxSettings.quickPressDelay)q=new Date;else{q=new Date;if(!a.ctrlKey&&!a.metaKey)break;if((!searchBoxSettings.keySettings.ctrlAltF||!a.altKey)&&(!searchBoxSettings.keySettings.ctrlShiftF||
!a.shiftKey))break}if(searchBoxSettings.isOpen){s(highlighter.c+1);break}B();break;case highlighter.w:searchBoxSettings.keySettings.f2&&(searchBoxSettings.isOpen?s(highlighter.c+1):B())}}var o=[];this.a=[];this.c=-1;this.e=e;var z={},k=e,v=[],w=[],L=[];this.h=e;this.f=this.i=!1;var U=document.body,f=document.body;this.v=70;this.w=113;var q=new Date;this.r=!0;var ba=27,O=RegExp(/[\(\)\/\s.,;'"\[\]!?-]/g),r=e,C=e,M=new x(0,0),D=e;this.o=["rgba(255,117,117,1)","rgba(75,254,120,1)","rgba(255,121,225,1)",
"rgba(223,223,0,1)","rgba(231,122,254,1)","rgba(134,188,255,1)","rgba(162,122,254,1)"];this.s=["rgba(255,117,117,0.6)","rgba(75,254,120,0.6)","rgba(255,121,225,0.6)","rgba(223,223,0,0.6)","rgba(231,122,254,0.6)","rgba(134,188,255,0.6)","rgba(162,122,254,0.6)"];String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"").replace(/\s{2,}/g," ")};this.j=function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop;while(a=a.offsetParent)}return new x(b,c)};this.p=function(a){highlighter.f=
!0;highlighter.d();w=a;if(!(w==e||w.length==0)){for(var b=0;b<o.length;b++){var c=o[b];if(c.b.parentNode!=e){var d;var g=c,i=a,f=T(g.n,g.z,i);if(f.length==0)d=e;else{d=[];for(var h=0,j=0;j<f.length;j++){d.push(document.createTextNode(g.content.substring(h,f[j].g)));var l=L[f[j].m%highlighter.o.length].A,h=highlighter.o[l],l=highlighter.s[l],k=document.createElement("my");k.style.setProperty("background-color",h);k.style.setProperty("border","1px solid black");k.style.setProperty("-webkit-border-radius",
"3px");k.style.setProperty("font-weight","bold");k.innerHTML=g.content.substring(f[j].g,f[j].q);h=new m(k,i[f[j].m],h);z[i[f[j].m]]=l;highlighter.a.push(h);d.push(k);h=f[j].q}g.content.length!=h&&d.push(document.createTextNode(g.content.substring(h,g.content.length)));g=document.createElement("mycontainer");for(j=0;j<d.length;j++)g.appendChild(d[j]);d=g}if(d!=e)j=c.b,c.l=d,c.b.parentNode.replaceChild(d,j)}}for(b=0;b<highlighter.a.length;b++)highlighter.a[b].position=highlighter.j(highlighter.a[b].b);
F();if(searchBoxSettings.enableSVG)for(a=0;a<highlighter.a.length;a++)for(b=a+1;b<highlighter.a.length;b++)if(highlighter.a[a].k!=highlighter.a[b].k&&highlighter.a[a].b.parentNode.parentNode==highlighter.a[b].b.parentNode.parentNode)c=highlighter.a[a].position.x,d=highlighter.a[a].position.y,j=highlighter.a[b].position.x,g=highlighter.a[b].position.y,i=document.getElementById("svgLines"),i==e&&(i=document.createElementNS("http://www.w3.org/2000/svg","svg"),i.setAttribute("id","svgLines"),i.style.setProperty("position",
"absolute"),i.style.setProperty("width",document.width.toString()),i.style.setProperty("height",document.height.toString()),i.style.setProperty("pointer-events","none"),document.body.insertBefore(i,document.body.firstChild)),f=document.createElementNS("http://www.w3.org/2000/svg","line"),f.setAttributeNS("","x1",c),f.setAttributeNS("","y1",d),f.setAttributeNS("","x2",j),f.setAttributeNS("","y2",g),f.style.setProperty("stroke","rgba(0,0,0,0.1)"),f.style.setProperty("stroke-width","2"),i.appendChild(f);
Y();I();highlighter.c>=0&&G(highlighter.c)}highlighter.f=!1};this.d=function(){highlighter.i=!0;document.getElementById("svgLines")!=e&&document.body.removeChild(document.getElementById("svgLines"));highlighter.a=[];z={};F();var a=document.getElementById("advancedSearch-updown");a!=e&&(a.style["border-color"]="");for(a=0;a<o.length;a++){var b=o[a],c=b.b,d=b.l;if(!(c==e||d==e))b.l.parentNode.replaceChild(c,d),b.l=e}A();highlighter.i=!1};this.checkredirecturl=function(a){if(searchBoxSettings.parseReferrer&&
a!=e&&a.indexOf(".google.")!=-1&&a.indexOf("q=")!=-1){a=K(a);if(a!=e)C=searchBoxSettings.searchText=a,h().value=a;storeSearchBoxSettings(!1)}};this.searchBoxSettingsRefreshed=function(){if(h()!=e){if(searchBoxSettings.searchText.length>0&&searchBoxSettings.storeSearchText&&h().value.length==0)h().value=searchBoxSettings.searchText.trim(),C=searchBoxSettings.searchText.trim();searchBoxSettings.reOpen&&searchBoxSettings.isOpen&&(B(),t())}};this.t=function(){highlighter.h=e;highlighter.d();E();searchBoxSettings.isOpen&&
highlighter.p(w)};this.u=function(){typeof Snowball!="undefined"&&(r=new Snowball("english"),highlighter.d(),E(),X(),getSearchBoxSettings(),window.addEventListener("keyup",aa,!1),searchBoxSettings.showDeleteOnHover&&(h().addEventListener("input",u,!1),h().addEventListener("keyup",u,!1),document.getElementById("advancedSearch-delWordButton").addEventListener("click",Z,!1),h().addEventListener("mousemove",$,!1)))}};document.addEventListener("DOMContentLoaded",highlighter.u(),!1);
document.addEventListener("DOMSubtreeModified",function(m){if(typeof Snowball!="undefined"&&!highlighter.i&&!highlighter.f&&m.target.nodeName!="svg"&&m.target.nodeName!="MY"&&m.target.nodeName!="ADVANCEDSEARCH-DEL"&&m.target.nodeName!="BODY"&&m.target.nodeName!="HTML"&&!(m.target.id!=e&&m.target.id.indexOf("advancedSearch-")==0))highlighter.h!=e&&clearTimeout(highlighter.h),highlighter.h=setTimeout(highlighter.t,3E3)},!1);
